name: nagwa_task
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  shimmer: ^3.0.0
  sizer: ^3.0.5

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  hive_ce_generator: ^1.8.2
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  very_good_analysis: ^7.0.0

dependency_overrides:
  source_gen: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/gen/lottie/
    - assets/gen/images/
    - assets/gen/icons/

flutter_intl:
  enabled: true

flutter_assets:
  assets_path: assets/gen/
  output_path: lib/core/utils/
  filename: assets.dart
  field_prefix: null
